package de.greenrobot.daogenerator.gentest;

import java.util.Date;

import de.greenrobot.daogenerator.Entity;
import de.greenrobot.daogenerator.Schema;

public class EProdCollection {
    public static void addEntity(Schema schema) {
        Entity entity = schema.addEntity(EProdCollection.class.getSimpleName());
        entity.addIdProperty().autoincrement();
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.ID
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addLongProperty("prodCollectionId").columnName(
                "prodCollectionId");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.STATUS
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addStringProperty("status").columnName("status");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.CREATED
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addDateProperty("created").columnName("created");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.LASTMOD
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addDateProperty("lastmod").columnName("lastmod");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.VERSION
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addLongProperty("version").columnName("version");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.SALES_ID
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addLongProperty("salesId").columnName("salesId");
        /**
         * This field was generated by Apache iBATIS ibator. This field
         * corresponds to the database column prod_collection.PROD_ID
         * 
         * @ibatorgenerated Mon May 12 10:56:31 CST 2014
         */
        entity.addLongProperty("prodId").columnName("prodId");
    }
}