package com.finshine.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.finshine.dao.EAdvertisement;
import com.finshine.dao.EAnnualIncomExpend;
import com.finshine.dao.EAppProd;
import com.finshine.dao.EArticle;
import com.finshine.dao.EArticleAd;
import com.finshine.dao.EAssetInfo;
import com.finshine.dao.EContactNote;
import com.finshine.dao.ECustomer;
import com.finshine.dao.ENotice;
import com.finshine.dao.EPhoto;
import com.finshine.dao.EProdAppointment;
import com.finshine.dao.EProdCollection;
import com.finshine.dao.EProdInvestMent;
import com.finshine.dao.EProdLike;
import com.finshine.dao.EProdReleasestrategy;
import com.finshine.dao.EProduct;
import com.finshine.dao.EProductSearch;
import com.finshine.dao.ESalesAppProd;
import com.finshine.dao.ETodoItem;

import com.finshine.dao.EAdvertisementDao;
import com.finshine.dao.EAnnualIncomExpendDao;
import com.finshine.dao.EAppProdDao;
import com.finshine.dao.EArticleDao;
import com.finshine.dao.EArticleAdDao;
import com.finshine.dao.EAssetInfoDao;
import com.finshine.dao.EContactNoteDao;
import com.finshine.dao.ECustomerDao;
import com.finshine.dao.ENoticeDao;
import com.finshine.dao.EPhotoDao;
import com.finshine.dao.EProdAppointmentDao;
import com.finshine.dao.EProdCollectionDao;
import com.finshine.dao.EProdInvestMentDao;
import com.finshine.dao.EProdLikeDao;
import com.finshine.dao.EProdReleasestrategyDao;
import com.finshine.dao.EProductDao;
import com.finshine.dao.EProductSearchDao;
import com.finshine.dao.ESalesAppProdDao;
import com.finshine.dao.ETodoItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eAdvertisementDaoConfig;
    private final DaoConfig eAnnualIncomExpendDaoConfig;
    private final DaoConfig eAppProdDaoConfig;
    private final DaoConfig eArticleDaoConfig;
    private final DaoConfig eArticleAdDaoConfig;
    private final DaoConfig eAssetInfoDaoConfig;
    private final DaoConfig eContactNoteDaoConfig;
    private final DaoConfig eCustomerDaoConfig;
    private final DaoConfig eNoticeDaoConfig;
    private final DaoConfig ePhotoDaoConfig;
    private final DaoConfig eProdAppointmentDaoConfig;
    private final DaoConfig eProdCollectionDaoConfig;
    private final DaoConfig eProdInvestMentDaoConfig;
    private final DaoConfig eProdLikeDaoConfig;
    private final DaoConfig eProdReleasestrategyDaoConfig;
    private final DaoConfig eProductDaoConfig;
    private final DaoConfig eProductSearchDaoConfig;
    private final DaoConfig eSalesAppProdDaoConfig;
    private final DaoConfig eTodoItemDaoConfig;

    private final EAdvertisementDao eAdvertisementDao;
    private final EAnnualIncomExpendDao eAnnualIncomExpendDao;
    private final EAppProdDao eAppProdDao;
    private final EArticleDao eArticleDao;
    private final EArticleAdDao eArticleAdDao;
    private final EAssetInfoDao eAssetInfoDao;
    private final EContactNoteDao eContactNoteDao;
    private final ECustomerDao eCustomerDao;
    private final ENoticeDao eNoticeDao;
    private final EPhotoDao ePhotoDao;
    private final EProdAppointmentDao eProdAppointmentDao;
    private final EProdCollectionDao eProdCollectionDao;
    private final EProdInvestMentDao eProdInvestMentDao;
    private final EProdLikeDao eProdLikeDao;
    private final EProdReleasestrategyDao eProdReleasestrategyDao;
    private final EProductDao eProductDao;
    private final EProductSearchDao eProductSearchDao;
    private final ESalesAppProdDao eSalesAppProdDao;
    private final ETodoItemDao eTodoItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eAdvertisementDaoConfig = daoConfigMap.get(EAdvertisementDao.class).clone();
        eAdvertisementDaoConfig.initIdentityScope(type);

        eAnnualIncomExpendDaoConfig = daoConfigMap.get(EAnnualIncomExpendDao.class).clone();
        eAnnualIncomExpendDaoConfig.initIdentityScope(type);

        eAppProdDaoConfig = daoConfigMap.get(EAppProdDao.class).clone();
        eAppProdDaoConfig.initIdentityScope(type);

        eArticleDaoConfig = daoConfigMap.get(EArticleDao.class).clone();
        eArticleDaoConfig.initIdentityScope(type);

        eArticleAdDaoConfig = daoConfigMap.get(EArticleAdDao.class).clone();
        eArticleAdDaoConfig.initIdentityScope(type);

        eAssetInfoDaoConfig = daoConfigMap.get(EAssetInfoDao.class).clone();
        eAssetInfoDaoConfig.initIdentityScope(type);

        eContactNoteDaoConfig = daoConfigMap.get(EContactNoteDao.class).clone();
        eContactNoteDaoConfig.initIdentityScope(type);

        eCustomerDaoConfig = daoConfigMap.get(ECustomerDao.class).clone();
        eCustomerDaoConfig.initIdentityScope(type);

        eNoticeDaoConfig = daoConfigMap.get(ENoticeDao.class).clone();
        eNoticeDaoConfig.initIdentityScope(type);

        ePhotoDaoConfig = daoConfigMap.get(EPhotoDao.class).clone();
        ePhotoDaoConfig.initIdentityScope(type);

        eProdAppointmentDaoConfig = daoConfigMap.get(EProdAppointmentDao.class).clone();
        eProdAppointmentDaoConfig.initIdentityScope(type);

        eProdCollectionDaoConfig = daoConfigMap.get(EProdCollectionDao.class).clone();
        eProdCollectionDaoConfig.initIdentityScope(type);

        eProdInvestMentDaoConfig = daoConfigMap.get(EProdInvestMentDao.class).clone();
        eProdInvestMentDaoConfig.initIdentityScope(type);

        eProdLikeDaoConfig = daoConfigMap.get(EProdLikeDao.class).clone();
        eProdLikeDaoConfig.initIdentityScope(type);

        eProdReleasestrategyDaoConfig = daoConfigMap.get(EProdReleasestrategyDao.class).clone();
        eProdReleasestrategyDaoConfig.initIdentityScope(type);

        eProductDaoConfig = daoConfigMap.get(EProductDao.class).clone();
        eProductDaoConfig.initIdentityScope(type);

        eProductSearchDaoConfig = daoConfigMap.get(EProductSearchDao.class).clone();
        eProductSearchDaoConfig.initIdentityScope(type);

        eSalesAppProdDaoConfig = daoConfigMap.get(ESalesAppProdDao.class).clone();
        eSalesAppProdDaoConfig.initIdentityScope(type);

        eTodoItemDaoConfig = daoConfigMap.get(ETodoItemDao.class).clone();
        eTodoItemDaoConfig.initIdentityScope(type);

        eAdvertisementDao = new EAdvertisementDao(eAdvertisementDaoConfig, this);
        eAnnualIncomExpendDao = new EAnnualIncomExpendDao(eAnnualIncomExpendDaoConfig, this);
        eAppProdDao = new EAppProdDao(eAppProdDaoConfig, this);
        eArticleDao = new EArticleDao(eArticleDaoConfig, this);
        eArticleAdDao = new EArticleAdDao(eArticleAdDaoConfig, this);
        eAssetInfoDao = new EAssetInfoDao(eAssetInfoDaoConfig, this);
        eContactNoteDao = new EContactNoteDao(eContactNoteDaoConfig, this);
        eCustomerDao = new ECustomerDao(eCustomerDaoConfig, this);
        eNoticeDao = new ENoticeDao(eNoticeDaoConfig, this);
        ePhotoDao = new EPhotoDao(ePhotoDaoConfig, this);
        eProdAppointmentDao = new EProdAppointmentDao(eProdAppointmentDaoConfig, this);
        eProdCollectionDao = new EProdCollectionDao(eProdCollectionDaoConfig, this);
        eProdInvestMentDao = new EProdInvestMentDao(eProdInvestMentDaoConfig, this);
        eProdLikeDao = new EProdLikeDao(eProdLikeDaoConfig, this);
        eProdReleasestrategyDao = new EProdReleasestrategyDao(eProdReleasestrategyDaoConfig, this);
        eProductDao = new EProductDao(eProductDaoConfig, this);
        eProductSearchDao = new EProductSearchDao(eProductSearchDaoConfig, this);
        eSalesAppProdDao = new ESalesAppProdDao(eSalesAppProdDaoConfig, this);
        eTodoItemDao = new ETodoItemDao(eTodoItemDaoConfig, this);

        registerDao(EAdvertisement.class, eAdvertisementDao);
        registerDao(EAnnualIncomExpend.class, eAnnualIncomExpendDao);
        registerDao(EAppProd.class, eAppProdDao);
        registerDao(EArticle.class, eArticleDao);
        registerDao(EArticleAd.class, eArticleAdDao);
        registerDao(EAssetInfo.class, eAssetInfoDao);
        registerDao(EContactNote.class, eContactNoteDao);
        registerDao(ECustomer.class, eCustomerDao);
        registerDao(ENotice.class, eNoticeDao);
        registerDao(EPhoto.class, ePhotoDao);
        registerDao(EProdAppointment.class, eProdAppointmentDao);
        registerDao(EProdCollection.class, eProdCollectionDao);
        registerDao(EProdInvestMent.class, eProdInvestMentDao);
        registerDao(EProdLike.class, eProdLikeDao);
        registerDao(EProdReleasestrategy.class, eProdReleasestrategyDao);
        registerDao(EProduct.class, eProductDao);
        registerDao(EProductSearch.class, eProductSearchDao);
        registerDao(ESalesAppProd.class, eSalesAppProdDao);
        registerDao(ETodoItem.class, eTodoItemDao);
    }
    
    public void clear() {
        eAdvertisementDaoConfig.getIdentityScope().clear();
        eAnnualIncomExpendDaoConfig.getIdentityScope().clear();
        eAppProdDaoConfig.getIdentityScope().clear();
        eArticleDaoConfig.getIdentityScope().clear();
        eArticleAdDaoConfig.getIdentityScope().clear();
        eAssetInfoDaoConfig.getIdentityScope().clear();
        eContactNoteDaoConfig.getIdentityScope().clear();
        eCustomerDaoConfig.getIdentityScope().clear();
        eNoticeDaoConfig.getIdentityScope().clear();
        ePhotoDaoConfig.getIdentityScope().clear();
        eProdAppointmentDaoConfig.getIdentityScope().clear();
        eProdCollectionDaoConfig.getIdentityScope().clear();
        eProdInvestMentDaoConfig.getIdentityScope().clear();
        eProdLikeDaoConfig.getIdentityScope().clear();
        eProdReleasestrategyDaoConfig.getIdentityScope().clear();
        eProductDaoConfig.getIdentityScope().clear();
        eProductSearchDaoConfig.getIdentityScope().clear();
        eSalesAppProdDaoConfig.getIdentityScope().clear();
        eTodoItemDaoConfig.getIdentityScope().clear();
    }

    public EAdvertisementDao getEAdvertisementDao() {
        return eAdvertisementDao;
    }

    public EAnnualIncomExpendDao getEAnnualIncomExpendDao() {
        return eAnnualIncomExpendDao;
    }

    public EAppProdDao getEAppProdDao() {
        return eAppProdDao;
    }

    public EArticleDao getEArticleDao() {
        return eArticleDao;
    }

    public EArticleAdDao getEArticleAdDao() {
        return eArticleAdDao;
    }

    public EAssetInfoDao getEAssetInfoDao() {
        return eAssetInfoDao;
    }

    public EContactNoteDao getEContactNoteDao() {
        return eContactNoteDao;
    }

    public ECustomerDao getECustomerDao() {
        return eCustomerDao;
    }

    public ENoticeDao getENoticeDao() {
        return eNoticeDao;
    }

    public EPhotoDao getEPhotoDao() {
        return ePhotoDao;
    }

    public EProdAppointmentDao getEProdAppointmentDao() {
        return eProdAppointmentDao;
    }

    public EProdCollectionDao getEProdCollectionDao() {
        return eProdCollectionDao;
    }

    public EProdInvestMentDao getEProdInvestMentDao() {
        return eProdInvestMentDao;
    }

    public EProdLikeDao getEProdLikeDao() {
        return eProdLikeDao;
    }

    public EProdReleasestrategyDao getEProdReleasestrategyDao() {
        return eProdReleasestrategyDao;
    }

    public EProductDao getEProductDao() {
        return eProductDao;
    }

    public EProductSearchDao getEProductSearchDao() {
        return eProductSearchDao;
    }

    public ESalesAppProdDao getESalesAppProdDao() {
        return eSalesAppProdDao;
    }

    public ETodoItemDao getETodoItemDao() {
        return eTodoItemDao;
    }

}
