package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EADVERTISEMENT.
 */
public class EAdvertisement implements java.io.Serializable {

    private Long id;
    private Long advertisementId;
    private Long articleId;
    private String imageAd;
    private java.util.Date created;
    private java.util.Date lastmod;
    private String status;

    public EAdvertisement() {
    }

    public EAdvertisement(Long id) {
        this.id = id;
    }

    public EAdvertisement(Long id, Long advertisementId, Long articleId, String imageAd, java.util.Date created, java.util.Date lastmod, String status) {
        this.id = id;
        this.advertisementId = advertisementId;
        this.articleId = articleId;
        this.imageAd = imageAd;
        this.created = created;
        this.lastmod = lastmod;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAdvertisementId() {
        return advertisementId;
    }

    public void setAdvertisementId(Long advertisementId) {
        this.advertisementId = advertisementId;
    }

    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public String getImageAd() {
        return imageAd;
    }

    public void setImageAd(String imageAd) {
        this.imageAd = imageAd;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
