package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EANNUAL_INCOM_EXPEND.
 */
public class EAnnualIncomExpend implements java.io.Serializable {

    private Long id;
    private Long annualincomexpendId;
    private Long customerId;
    private Long income;
    private Long spouseIncome;
    private Long endBonus;
    private Long rental;
    private Long interest;
    private Long dividends;
    private Long otherDividends;
    private Long otherFixIncome;
    private Long otherUnfixIncome;
    private Long totalIncome;
    private Long livingCost;
    private Long housExpense;
    private Long medicExpense;
    private Long eduExpense;
    private Long insurance;
    private Long travel;
    private Long alimony;
    private Long otherFixExpense;
    private Long otherUnfixExpense;
    private Long totalExpenditure;
    private Long annualBalance;
    private String historyExperience;

    public EAnnualIncomExpend() {
    }

    public EAnnualIncomExpend(Long id) {
        this.id = id;
    }

    public EAnnualIncomExpend(Long id, Long annualincomexpendId, Long customerId, Long income, Long spouseIncome, Long endBonus, Long rental, Long interest, Long dividends, Long otherDividends, Long otherFixIncome, Long otherUnfixIncome, Long totalIncome, Long livingCost, Long housExpense, Long medicExpense, Long eduExpense, Long insurance, Long travel, Long alimony, Long otherFixExpense, Long otherUnfixExpense, Long totalExpenditure, Long annualBalance, String historyExperience) {
        this.id = id;
        this.annualincomexpendId = annualincomexpendId;
        this.customerId = customerId;
        this.income = income;
        this.spouseIncome = spouseIncome;
        this.endBonus = endBonus;
        this.rental = rental;
        this.interest = interest;
        this.dividends = dividends;
        this.otherDividends = otherDividends;
        this.otherFixIncome = otherFixIncome;
        this.otherUnfixIncome = otherUnfixIncome;
        this.totalIncome = totalIncome;
        this.livingCost = livingCost;
        this.housExpense = housExpense;
        this.medicExpense = medicExpense;
        this.eduExpense = eduExpense;
        this.insurance = insurance;
        this.travel = travel;
        this.alimony = alimony;
        this.otherFixExpense = otherFixExpense;
        this.otherUnfixExpense = otherUnfixExpense;
        this.totalExpenditure = totalExpenditure;
        this.annualBalance = annualBalance;
        this.historyExperience = historyExperience;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAnnualincomexpendId() {
        return annualincomexpendId;
    }

    public void setAnnualincomexpendId(Long annualincomexpendId) {
        this.annualincomexpendId = annualincomexpendId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Long getIncome() {
        return income;
    }

    public void setIncome(Long income) {
        this.income = income;
    }

    public Long getSpouseIncome() {
        return spouseIncome;
    }

    public void setSpouseIncome(Long spouseIncome) {
        this.spouseIncome = spouseIncome;
    }

    public Long getEndBonus() {
        return endBonus;
    }

    public void setEndBonus(Long endBonus) {
        this.endBonus = endBonus;
    }

    public Long getRental() {
        return rental;
    }

    public void setRental(Long rental) {
        this.rental = rental;
    }

    public Long getInterest() {
        return interest;
    }

    public void setInterest(Long interest) {
        this.interest = interest;
    }

    public Long getDividends() {
        return dividends;
    }

    public void setDividends(Long dividends) {
        this.dividends = dividends;
    }

    public Long getOtherDividends() {
        return otherDividends;
    }

    public void setOtherDividends(Long otherDividends) {
        this.otherDividends = otherDividends;
    }

    public Long getOtherFixIncome() {
        return otherFixIncome;
    }

    public void setOtherFixIncome(Long otherFixIncome) {
        this.otherFixIncome = otherFixIncome;
    }

    public Long getOtherUnfixIncome() {
        return otherUnfixIncome;
    }

    public void setOtherUnfixIncome(Long otherUnfixIncome) {
        this.otherUnfixIncome = otherUnfixIncome;
    }

    public Long getTotalIncome() {
        return totalIncome;
    }

    public void setTotalIncome(Long totalIncome) {
        this.totalIncome = totalIncome;
    }

    public Long getLivingCost() {
        return livingCost;
    }

    public void setLivingCost(Long livingCost) {
        this.livingCost = livingCost;
    }

    public Long getHousExpense() {
        return housExpense;
    }

    public void setHousExpense(Long housExpense) {
        this.housExpense = housExpense;
    }

    public Long getMedicExpense() {
        return medicExpense;
    }

    public void setMedicExpense(Long medicExpense) {
        this.medicExpense = medicExpense;
    }

    public Long getEduExpense() {
        return eduExpense;
    }

    public void setEduExpense(Long eduExpense) {
        this.eduExpense = eduExpense;
    }

    public Long getInsurance() {
        return insurance;
    }

    public void setInsurance(Long insurance) {
        this.insurance = insurance;
    }

    public Long getTravel() {
        return travel;
    }

    public void setTravel(Long travel) {
        this.travel = travel;
    }

    public Long getAlimony() {
        return alimony;
    }

    public void setAlimony(Long alimony) {
        this.alimony = alimony;
    }

    public Long getOtherFixExpense() {
        return otherFixExpense;
    }

    public void setOtherFixExpense(Long otherFixExpense) {
        this.otherFixExpense = otherFixExpense;
    }

    public Long getOtherUnfixExpense() {
        return otherUnfixExpense;
    }

    public void setOtherUnfixExpense(Long otherUnfixExpense) {
        this.otherUnfixExpense = otherUnfixExpense;
    }

    public Long getTotalExpenditure() {
        return totalExpenditure;
    }

    public void setTotalExpenditure(Long totalExpenditure) {
        this.totalExpenditure = totalExpenditure;
    }

    public Long getAnnualBalance() {
        return annualBalance;
    }

    public void setAnnualBalance(Long annualBalance) {
        this.annualBalance = annualBalance;
    }

    public String getHistoryExperience() {
        return historyExperience;
    }

    public void setHistoryExperience(String historyExperience) {
        this.historyExperience = historyExperience;
    }

}
