package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EAPP_PROD.
 */
public class EAppProd implements java.io.Serializable {

    private Long id;
    private Long appProdId;
    private String prodName;
    private String prodMyid;
    private String prodAdmin;
    private Long userId;
    private java.util.Date created;
    private Float prodAmount;
    private Long prodStatus;

    public EAppProd() {
    }

    public EAppProd(Long id) {
        this.id = id;
    }

    public EAppProd(Long id, Long appProdId, String prodName, String prodMyid, String prodAdmin, Long userId, java.util.Date created, Float prodAmount, Long prodStatus) {
        this.id = id;
        this.appProdId = appProdId;
        this.prodName = prodName;
        this.prodMyid = prodMyid;
        this.prodAdmin = prodAdmin;
        this.userId = userId;
        this.created = created;
        this.prodAmount = prodAmount;
        this.prodStatus = prodStatus;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAppProdId() {
        return appProdId;
    }

    public void setAppProdId(Long appProdId) {
        this.appProdId = appProdId;
    }

    public String getProdName() {
        return prodName;
    }

    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    public String getProdMyid() {
        return prodMyid;
    }

    public void setProdMyid(String prodMyid) {
        this.prodMyid = prodMyid;
    }

    public String getProdAdmin() {
        return prodAdmin;
    }

    public void setProdAdmin(String prodAdmin) {
        this.prodAdmin = prodAdmin;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public Float getProdAmount() {
        return prodAmount;
    }

    public void setProdAmount(Float prodAmount) {
        this.prodAmount = prodAmount;
    }

    public Long getProdStatus() {
        return prodStatus;
    }

    public void setProdStatus(Long prodStatus) {
        this.prodStatus = prodStatus;
    }

}
