package com.finshine.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.finshine.dao.EArticleAd;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EARTICLE_AD.
*/
public class EArticleAdDao extends AbstractDao<EArticleAd, Long> {

    public static final String TABLENAME = "EARTICLE_AD";

    /**
     * Properties of entity EArticleAd.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ArticleAdId = new Property(1, Long.class, "articleAdId", false, "articleAdId");
        public final static Property ArticleId = new Property(2, Long.class, "articleId", false, "articleId");
        public final static Property Created = new Property(3, java.util.Date.class, "created", false, "created");
        public final static Property Lastmod = new Property(4, java.util.Date.class, "lastmod", false, "lastmod");
        public final static Property Status = new Property(5, String.class, "status", false, "status");
        public final static Property Title = new Property(6, String.class, "title", false, "title");
    };


    public EArticleAdDao(DaoConfig config) {
        super(config);
    }
    
    public EArticleAdDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EARTICLE_AD' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'articleAdId' INTEGER," + // 1: articleAdId
                "'articleId' INTEGER," + // 2: articleId
                "'created' INTEGER," + // 3: created
                "'lastmod' INTEGER," + // 4: lastmod
                "'status' TEXT," + // 5: status
                "'title' TEXT);"); // 6: title
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EARTICLE_AD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EArticleAd entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long articleAdId = entity.getArticleAdId();
        if (articleAdId != null) {
            stmt.bindLong(2, articleAdId);
        }
 
        Long articleId = entity.getArticleId();
        if (articleId != null) {
            stmt.bindLong(3, articleId);
        }
 
        java.util.Date created = entity.getCreated();
        if (created != null) {
            stmt.bindLong(4, created.getTime());
        }
 
        java.util.Date lastmod = entity.getLastmod();
        if (lastmod != null) {
            stmt.bindLong(5, lastmod.getTime());
        }
 
        String status = entity.getStatus();
        if (status != null) {
            stmt.bindString(6, status);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(7, title);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EArticleAd readEntity(Cursor cursor, int offset) {
        EArticleAd entity = new EArticleAd( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // articleAdId
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // articleId
            cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)), // created
            cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)), // lastmod
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // status
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // title
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EArticleAd entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setArticleAdId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setArticleId(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setCreated(cursor.isNull(offset + 3) ? null : new java.util.Date(cursor.getLong(offset + 3)));
        entity.setLastmod(cursor.isNull(offset + 4) ? null : new java.util.Date(cursor.getLong(offset + 4)));
        entity.setStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTitle(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EArticleAd entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EArticleAd entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
