package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EARTICLE_AD.
 */
public class EArticleAd implements java.io.Serializable {

    private Long id;
    private Long articleAdId;
    private Long articleId;
    private java.util.Date created;
    private java.util.Date lastmod;
    private String status;
    private String title;

    public EArticleAd() {
    }

    public EArticleAd(Long id) {
        this.id = id;
    }

    public EArticleAd(Long id, Long articleAdId, Long articleId, java.util.Date created, java.util.Date lastmod, String status, String title) {
        this.id = id;
        this.articleAdId = articleAdId;
        this.articleId = articleId;
        this.created = created;
        this.lastmod = lastmod;
        this.status = status;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getArticleAdId() {
        return articleAdId;
    }

    public void setArticleAdId(Long articleAdId) {
        this.articleAdId = articleAdId;
    }

    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
