package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EASSET_INFO.
 */
public class EAssetInfo implements java.io.Serializable {

    private Long id;
    private Long assetInfoId;
    private Long customerId;
    private String goal;
    private Long cash;
    private Float cashReturn;
    private Long demanDeposit;
    private Float demanDepositReturn;
    private Long fixDeposit;
    private Float fixDepositReturn;
    private Long stock;
    private Float stockReturn;
    private Long fund;
    private Float fundReturn;
    private Long bond;
    private Float bondReturn;
    private Long estate;
    private Float estateReturn;
    private Long otherAsset;
    private Float otherAssetReturn;
    private Long totalAsset;
    private Long houseFundLoan;
    private Long houseBusinessLoan;
    private Long carLoan;
    private Long consumerLoan;
    private Long renovationLoan;
    private Long privateLoan;
    private Long unpaidCreditCard;
    private Long otherLoan;
    private Long totalLoan;
    private Long netAsset;

    public EAssetInfo() {
    }

    public EAssetInfo(Long id) {
        this.id = id;
    }

    public EAssetInfo(Long id, Long assetInfoId, Long customerId, String goal, Long cash, Float cashReturn, Long demanDeposit, Float demanDepositReturn, Long fixDeposit, Float fixDepositReturn, Long stock, Float stockReturn, Long fund, Float fundReturn, Long bond, Float bondReturn, Long estate, Float estateReturn, Long otherAsset, Float otherAssetReturn, Long totalAsset, Long houseFundLoan, Long houseBusinessLoan, Long carLoan, Long consumerLoan, Long renovationLoan, Long privateLoan, Long unpaidCreditCard, Long otherLoan, Long totalLoan, Long netAsset) {
        this.id = id;
        this.assetInfoId = assetInfoId;
        this.customerId = customerId;
        this.goal = goal;
        this.cash = cash;
        this.cashReturn = cashReturn;
        this.demanDeposit = demanDeposit;
        this.demanDepositReturn = demanDepositReturn;
        this.fixDeposit = fixDeposit;
        this.fixDepositReturn = fixDepositReturn;
        this.stock = stock;
        this.stockReturn = stockReturn;
        this.fund = fund;
        this.fundReturn = fundReturn;
        this.bond = bond;
        this.bondReturn = bondReturn;
        this.estate = estate;
        this.estateReturn = estateReturn;
        this.otherAsset = otherAsset;
        this.otherAssetReturn = otherAssetReturn;
        this.totalAsset = totalAsset;
        this.houseFundLoan = houseFundLoan;
        this.houseBusinessLoan = houseBusinessLoan;
        this.carLoan = carLoan;
        this.consumerLoan = consumerLoan;
        this.renovationLoan = renovationLoan;
        this.privateLoan = privateLoan;
        this.unpaidCreditCard = unpaidCreditCard;
        this.otherLoan = otherLoan;
        this.totalLoan = totalLoan;
        this.netAsset = netAsset;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getAssetInfoId() {
        return assetInfoId;
    }

    public void setAssetInfoId(Long assetInfoId) {
        this.assetInfoId = assetInfoId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getGoal() {
        return goal;
    }

    public void setGoal(String goal) {
        this.goal = goal;
    }

    public Long getCash() {
        return cash;
    }

    public void setCash(Long cash) {
        this.cash = cash;
    }

    public Float getCashReturn() {
        return cashReturn;
    }

    public void setCashReturn(Float cashReturn) {
        this.cashReturn = cashReturn;
    }

    public Long getDemanDeposit() {
        return demanDeposit;
    }

    public void setDemanDeposit(Long demanDeposit) {
        this.demanDeposit = demanDeposit;
    }

    public Float getDemanDepositReturn() {
        return demanDepositReturn;
    }

    public void setDemanDepositReturn(Float demanDepositReturn) {
        this.demanDepositReturn = demanDepositReturn;
    }

    public Long getFixDeposit() {
        return fixDeposit;
    }

    public void setFixDeposit(Long fixDeposit) {
        this.fixDeposit = fixDeposit;
    }

    public Float getFixDepositReturn() {
        return fixDepositReturn;
    }

    public void setFixDepositReturn(Float fixDepositReturn) {
        this.fixDepositReturn = fixDepositReturn;
    }

    public Long getStock() {
        return stock;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public Float getStockReturn() {
        return stockReturn;
    }

    public void setStockReturn(Float stockReturn) {
        this.stockReturn = stockReturn;
    }

    public Long getFund() {
        return fund;
    }

    public void setFund(Long fund) {
        this.fund = fund;
    }

    public Float getFundReturn() {
        return fundReturn;
    }

    public void setFundReturn(Float fundReturn) {
        this.fundReturn = fundReturn;
    }

    public Long getBond() {
        return bond;
    }

    public void setBond(Long bond) {
        this.bond = bond;
    }

    public Float getBondReturn() {
        return bondReturn;
    }

    public void setBondReturn(Float bondReturn) {
        this.bondReturn = bondReturn;
    }

    public Long getEstate() {
        return estate;
    }

    public void setEstate(Long estate) {
        this.estate = estate;
    }

    public Float getEstateReturn() {
        return estateReturn;
    }

    public void setEstateReturn(Float estateReturn) {
        this.estateReturn = estateReturn;
    }

    public Long getOtherAsset() {
        return otherAsset;
    }

    public void setOtherAsset(Long otherAsset) {
        this.otherAsset = otherAsset;
    }

    public Float getOtherAssetReturn() {
        return otherAssetReturn;
    }

    public void setOtherAssetReturn(Float otherAssetReturn) {
        this.otherAssetReturn = otherAssetReturn;
    }

    public Long getTotalAsset() {
        return totalAsset;
    }

    public void setTotalAsset(Long totalAsset) {
        this.totalAsset = totalAsset;
    }

    public Long getHouseFundLoan() {
        return houseFundLoan;
    }

    public void setHouseFundLoan(Long houseFundLoan) {
        this.houseFundLoan = houseFundLoan;
    }

    public Long getHouseBusinessLoan() {
        return houseBusinessLoan;
    }

    public void setHouseBusinessLoan(Long houseBusinessLoan) {
        this.houseBusinessLoan = houseBusinessLoan;
    }

    public Long getCarLoan() {
        return carLoan;
    }

    public void setCarLoan(Long carLoan) {
        this.carLoan = carLoan;
    }

    public Long getConsumerLoan() {
        return consumerLoan;
    }

    public void setConsumerLoan(Long consumerLoan) {
        this.consumerLoan = consumerLoan;
    }

    public Long getRenovationLoan() {
        return renovationLoan;
    }

    public void setRenovationLoan(Long renovationLoan) {
        this.renovationLoan = renovationLoan;
    }

    public Long getPrivateLoan() {
        return privateLoan;
    }

    public void setPrivateLoan(Long privateLoan) {
        this.privateLoan = privateLoan;
    }

    public Long getUnpaidCreditCard() {
        return unpaidCreditCard;
    }

    public void setUnpaidCreditCard(Long unpaidCreditCard) {
        this.unpaidCreditCard = unpaidCreditCard;
    }

    public Long getOtherLoan() {
        return otherLoan;
    }

    public void setOtherLoan(Long otherLoan) {
        this.otherLoan = otherLoan;
    }

    public Long getTotalLoan() {
        return totalLoan;
    }

    public void setTotalLoan(Long totalLoan) {
        this.totalLoan = totalLoan;
    }

    public Long getNetAsset() {
        return netAsset;
    }

    public void setNetAsset(Long netAsset) {
        this.netAsset = netAsset;
    }

}
