package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ECONTACT_NOTE.
 */
public class EContactNote implements java.io.Serializable {

    private Long id;
    private Long contactNoteId;
    private Long customerId;
    private Long salesId;
    private Long contactDate;
    private String title;
    private Long content;

    public EContactNote() {
    }

    public EContactNote(Long id) {
        this.id = id;
    }

    public EContactNote(Long id, Long contactNoteId, Long customerId, Long salesId, Long contactDate, String title, Long content) {
        this.id = id;
        this.contactNoteId = contactNoteId;
        this.customerId = customerId;
        this.salesId = salesId;
        this.contactDate = contactDate;
        this.title = title;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getContactNoteId() {
        return contactNoteId;
    }

    public void setContactNoteId(Long contactNoteId) {
        this.contactNoteId = contactNoteId;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public Long getSalesId() {
        return salesId;
    }

    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    public Long getContactDate() {
        return contactDate;
    }

    public void setContactDate(Long contactDate) {
        this.contactDate = contactDate;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Long getContent() {
        return content;
    }

    public void setContent(Long content) {
        this.content = content;
    }

}
