package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ENOTICE.
 */
public class ENotice implements java.io.Serializable {

    private Long id;
    private Long noticeId;
    private Long articleId;
    private String content;
    private java.util.Date created;
    private java.util.Date lastmod;
    private String status;

    public ENotice() {
    }

    public ENotice(Long id) {
        this.id = id;
    }

    public ENotice(Long id, Long noticeId, Long articleId, String content, java.util.Date created, java.util.Date lastmod, String status) {
        this.id = id;
        this.noticeId = noticeId;
        this.articleId = articleId;
        this.content = content;
        this.created = created;
        this.lastmod = lastmod;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNoticeId() {
        return noticeId;
    }

    public void setNoticeId(Long noticeId) {
        this.noticeId = noticeId;
    }

    public Long getArticleId() {
        return articleId;
    }

    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

}
