package com.finshine.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.finshine.dao.EPhoto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table EPHOTO.
*/
public class EPhotoDao extends AbstractDao<EPhoto, Long> {

    public static final String TABLENAME = "EPHOTO";

    /**
     * Properties of entity EPhoto.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PhotoId = new Property(1, Long.class, "photoId", false, "photoId");
        public final static Property MimeType = new Property(2, String.class, "mimeType", false, "mimeType");
        public final static Property PhotoData = new Property(3, byte[].class, "photoData", false, "photoData");
    };


    public EPhotoDao(DaoConfig config) {
        super(config);
    }
    
    public EPhotoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'EPHOTO' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'photoId' INTEGER," + // 1: photoId
                "'mimeType' TEXT," + // 2: mimeType
                "'photoData' BLOB);"); // 3: photoData
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'EPHOTO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, EPhoto entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long photoId = entity.getPhotoId();
        if (photoId != null) {
            stmt.bindLong(2, photoId);
        }
 
        String mimeType = entity.getMimeType();
        if (mimeType != null) {
            stmt.bindString(3, mimeType);
        }
 
        byte[] photoData = entity.getPhotoData();
        if (photoData != null) {
            stmt.bindBlob(4, photoData);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public EPhoto readEntity(Cursor cursor, int offset) {
        EPhoto entity = new EPhoto( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // photoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // mimeType
            cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3) // photoData
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, EPhoto entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPhotoId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMimeType(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhotoData(cursor.isNull(offset + 3) ? null : cursor.getBlob(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(EPhoto entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(EPhoto entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
