package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPRODUCT.
 */
public class EProduct implements java.io.Serializable {

    private Long id;
    private Long productId;
    private String status;
    private Long created;
    private Long lastmod;
    private Long version;
    private String prodMyid;
    private Long prodFirstType;
    private Long prodSecondtype;
    private Long prodStatus;
    private String prodElementsSrc;
    private String prodPptSrc;
    private String prodInstructionsSrc;
    private String prodContractSrc;
    private String prodNetreportSrc;
    private String prodTrainingSrc;
    private String prodName;
    private String prodHighLights;
    private String prodAdmin;
    private String prodPreference;
    private String prodPublisher;
    private String prodPubEmail;
    private Long prodOnDateTime;
    private Long prodEnDateTime;
    private Float prodSize;
    private Float prodTime;
    private Float prodYieldFloating;
    private Float prodYieldFixed;
    private Float prodPrice;
    private Float prodStart;
    private String prodCounterParty;
    private String prodUse;
    private String prodRepayment;
    private String prodRisk;
    private String prodIncomeType;
    private String prodReceipts;
    private String prodIncomeDateTime;
    private String prodCstTel;
    private String prodEscrowacCount;
    private Float prodCommissionBase;
    private String prodComment;
    private Long userId;
    private String prodCode;
    private Long prodTop;
    private String prodOnDateTimeStr;
    private String prodEnDateTimeStr;
    private Long isSave;
    private Long hotPoint;

    public EProduct() {
    }

    public EProduct(Long id) {
        this.id = id;
    }

    public EProduct(Long id, Long productId, String status, Long created, Long lastmod, Long version, String prodMyid, Long prodFirstType, Long prodSecondtype, Long prodStatus, String prodElementsSrc, String prodPptSrc, String prodInstructionsSrc, String prodContractSrc, String prodNetreportSrc, String prodTrainingSrc, String prodName, String prodHighLights, String prodAdmin, String prodPreference, String prodPublisher, String prodPubEmail, Long prodOnDateTime, Long prodEnDateTime, Float prodSize, Float prodTime, Float prodYieldFloating, Float prodYieldFixed, Float prodPrice, Float prodStart, String prodCounterParty, String prodUse, String prodRepayment, String prodRisk, String prodIncomeType, String prodReceipts, String prodIncomeDateTime, String prodCstTel, String prodEscrowacCount, Float prodCommissionBase, String prodComment, Long userId, String prodCode, Long prodTop, String prodOnDateTimeStr, String prodEnDateTimeStr, Long isSave, Long hotPoint) {
        this.id = id;
        this.productId = productId;
        this.status = status;
        this.created = created;
        this.lastmod = lastmod;
        this.version = version;
        this.prodMyid = prodMyid;
        this.prodFirstType = prodFirstType;
        this.prodSecondtype = prodSecondtype;
        this.prodStatus = prodStatus;
        this.prodElementsSrc = prodElementsSrc;
        this.prodPptSrc = prodPptSrc;
        this.prodInstructionsSrc = prodInstructionsSrc;
        this.prodContractSrc = prodContractSrc;
        this.prodNetreportSrc = prodNetreportSrc;
        this.prodTrainingSrc = prodTrainingSrc;
        this.prodName = prodName;
        this.prodHighLights = prodHighLights;
        this.prodAdmin = prodAdmin;
        this.prodPreference = prodPreference;
        this.prodPublisher = prodPublisher;
        this.prodPubEmail = prodPubEmail;
        this.prodOnDateTime = prodOnDateTime;
        this.prodEnDateTime = prodEnDateTime;
        this.prodSize = prodSize;
        this.prodTime = prodTime;
        this.prodYieldFloating = prodYieldFloating;
        this.prodYieldFixed = prodYieldFixed;
        this.prodPrice = prodPrice;
        this.prodStart = prodStart;
        this.prodCounterParty = prodCounterParty;
        this.prodUse = prodUse;
        this.prodRepayment = prodRepayment;
        this.prodRisk = prodRisk;
        this.prodIncomeType = prodIncomeType;
        this.prodReceipts = prodReceipts;
        this.prodIncomeDateTime = prodIncomeDateTime;
        this.prodCstTel = prodCstTel;
        this.prodEscrowacCount = prodEscrowacCount;
        this.prodCommissionBase = prodCommissionBase;
        this.prodComment = prodComment;
        this.userId = userId;
        this.prodCode = prodCode;
        this.prodTop = prodTop;
        this.prodOnDateTimeStr = prodOnDateTimeStr;
        this.prodEnDateTimeStr = prodEnDateTimeStr;
        this.isSave = isSave;
        this.hotPoint = hotPoint;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProductId() {
        return productId;
    }

    public void setProductId(Long productId) {
        this.productId = productId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public Long getLastmod() {
        return lastmod;
    }

    public void setLastmod(Long lastmod) {
        this.lastmod = lastmod;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getProdMyid() {
        return prodMyid;
    }

    public void setProdMyid(String prodMyid) {
        this.prodMyid = prodMyid;
    }

    public Long getProdFirstType() {
        return prodFirstType;
    }

    public void setProdFirstType(Long prodFirstType) {
        this.prodFirstType = prodFirstType;
    }

    public Long getProdSecondtype() {
        return prodSecondtype;
    }

    public void setProdSecondtype(Long prodSecondtype) {
        this.prodSecondtype = prodSecondtype;
    }

    public Long getProdStatus() {
        return prodStatus;
    }

    public void setProdStatus(Long prodStatus) {
        this.prodStatus = prodStatus;
    }

    public String getProdElementsSrc() {
        return prodElementsSrc;
    }

    public void setProdElementsSrc(String prodElementsSrc) {
        this.prodElementsSrc = prodElementsSrc;
    }

    public String getProdPptSrc() {
        return prodPptSrc;
    }

    public void setProdPptSrc(String prodPptSrc) {
        this.prodPptSrc = prodPptSrc;
    }

    public String getProdInstructionsSrc() {
        return prodInstructionsSrc;
    }

    public void setProdInstructionsSrc(String prodInstructionsSrc) {
        this.prodInstructionsSrc = prodInstructionsSrc;
    }

    public String getProdContractSrc() {
        return prodContractSrc;
    }

    public void setProdContractSrc(String prodContractSrc) {
        this.prodContractSrc = prodContractSrc;
    }

    public String getProdNetreportSrc() {
        return prodNetreportSrc;
    }

    public void setProdNetreportSrc(String prodNetreportSrc) {
        this.prodNetreportSrc = prodNetreportSrc;
    }

    public String getProdTrainingSrc() {
        return prodTrainingSrc;
    }

    public void setProdTrainingSrc(String prodTrainingSrc) {
        this.prodTrainingSrc = prodTrainingSrc;
    }

    public String getProdName() {
        return prodName;
    }

    public void setProdName(String prodName) {
        this.prodName = prodName;
    }

    public String getProdHighLights() {
        return prodHighLights;
    }

    public void setProdHighLights(String prodHighLights) {
        this.prodHighLights = prodHighLights;
    }

    public String getProdAdmin() {
        return prodAdmin;
    }

    public void setProdAdmin(String prodAdmin) {
        this.prodAdmin = prodAdmin;
    }

    public String getProdPreference() {
        return prodPreference;
    }

    public void setProdPreference(String prodPreference) {
        this.prodPreference = prodPreference;
    }

    public String getProdPublisher() {
        return prodPublisher;
    }

    public void setProdPublisher(String prodPublisher) {
        this.prodPublisher = prodPublisher;
    }

    public String getProdPubEmail() {
        return prodPubEmail;
    }

    public void setProdPubEmail(String prodPubEmail) {
        this.prodPubEmail = prodPubEmail;
    }

    public Long getProdOnDateTime() {
        return prodOnDateTime;
    }

    public void setProdOnDateTime(Long prodOnDateTime) {
        this.prodOnDateTime = prodOnDateTime;
    }

    public Long getProdEnDateTime() {
        return prodEnDateTime;
    }

    public void setProdEnDateTime(Long prodEnDateTime) {
        this.prodEnDateTime = prodEnDateTime;
    }

    public Float getProdSize() {
        return prodSize;
    }

    public void setProdSize(Float prodSize) {
        this.prodSize = prodSize;
    }

    public Float getProdTime() {
        return prodTime;
    }

    public void setProdTime(Float prodTime) {
        this.prodTime = prodTime;
    }

    public Float getProdYieldFloating() {
        return prodYieldFloating;
    }

    public void setProdYieldFloating(Float prodYieldFloating) {
        this.prodYieldFloating = prodYieldFloating;
    }

    public Float getProdYieldFixed() {
        return prodYieldFixed;
    }

    public void setProdYieldFixed(Float prodYieldFixed) {
        this.prodYieldFixed = prodYieldFixed;
    }

    public Float getProdPrice() {
        return prodPrice;
    }

    public void setProdPrice(Float prodPrice) {
        this.prodPrice = prodPrice;
    }

    public Float getProdStart() {
        return prodStart;
    }

    public void setProdStart(Float prodStart) {
        this.prodStart = prodStart;
    }

    public String getProdCounterParty() {
        return prodCounterParty;
    }

    public void setProdCounterParty(String prodCounterParty) {
        this.prodCounterParty = prodCounterParty;
    }

    public String getProdUse() {
        return prodUse;
    }

    public void setProdUse(String prodUse) {
        this.prodUse = prodUse;
    }

    public String getProdRepayment() {
        return prodRepayment;
    }

    public void setProdRepayment(String prodRepayment) {
        this.prodRepayment = prodRepayment;
    }

    public String getProdRisk() {
        return prodRisk;
    }

    public void setProdRisk(String prodRisk) {
        this.prodRisk = prodRisk;
    }

    public String getProdIncomeType() {
        return prodIncomeType;
    }

    public void setProdIncomeType(String prodIncomeType) {
        this.prodIncomeType = prodIncomeType;
    }

    public String getProdReceipts() {
        return prodReceipts;
    }

    public void setProdReceipts(String prodReceipts) {
        this.prodReceipts = prodReceipts;
    }

    public String getProdIncomeDateTime() {
        return prodIncomeDateTime;
    }

    public void setProdIncomeDateTime(String prodIncomeDateTime) {
        this.prodIncomeDateTime = prodIncomeDateTime;
    }

    public String getProdCstTel() {
        return prodCstTel;
    }

    public void setProdCstTel(String prodCstTel) {
        this.prodCstTel = prodCstTel;
    }

    public String getProdEscrowacCount() {
        return prodEscrowacCount;
    }

    public void setProdEscrowacCount(String prodEscrowacCount) {
        this.prodEscrowacCount = prodEscrowacCount;
    }

    public Float getProdCommissionBase() {
        return prodCommissionBase;
    }

    public void setProdCommissionBase(Float prodCommissionBase) {
        this.prodCommissionBase = prodCommissionBase;
    }

    public String getProdComment() {
        return prodComment;
    }

    public void setProdComment(String prodComment) {
        this.prodComment = prodComment;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getProdCode() {
        return prodCode;
    }

    public void setProdCode(String prodCode) {
        this.prodCode = prodCode;
    }

    public Long getProdTop() {
        return prodTop;
    }

    public void setProdTop(Long prodTop) {
        this.prodTop = prodTop;
    }

    public String getProdOnDateTimeStr() {
        return prodOnDateTimeStr;
    }

    public void setProdOnDateTimeStr(String prodOnDateTimeStr) {
        this.prodOnDateTimeStr = prodOnDateTimeStr;
    }

    public String getProdEnDateTimeStr() {
        return prodEnDateTimeStr;
    }

    public void setProdEnDateTimeStr(String prodEnDateTimeStr) {
        this.prodEnDateTimeStr = prodEnDateTimeStr;
    }

    public Long getIsSave() {
        return isSave;
    }

    public void setIsSave(Long isSave) {
        this.isSave = isSave;
    }

    public Long getHotPoint() {
        return hotPoint;
    }

    public void setHotPoint(Long hotPoint) {
        this.hotPoint = hotPoint;
    }

}
