package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPROD_COLLECTION.
 */
public class EProdCollection {

    private Long id;
    private Long prodCollectionId;
    private String status;
    private java.util.Date created;
    private java.util.Date lastmod;
    private Long version;
    private Long salesId;
    private Long prodId;

    public EProdCollection() {
    }

    public EProdCollection(Long id) {
        this.id = id;
    }

    public EProdCollection(Long id, Long prodCollectionId, String status, java.util.Date created, java.util.Date lastmod, Long version, Long salesId, Long prodId) {
        this.id = id;
        this.prodCollectionId = prodCollectionId;
        this.status = status;
        this.created = created;
        this.lastmod = lastmod;
        this.version = version;
        this.salesId = salesId;
        this.prodId = prodId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProdCollectionId() {
        return prodCollectionId;
    }

    public void setProdCollectionId(Long prodCollectionId) {
        this.prodCollectionId = prodCollectionId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getSalesId() {
        return salesId;
    }

    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    public Long getProdId() {
        return prodId;
    }

    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

}
