package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPROD_INVEST_MENT.
 */
public class EProdInvestMent implements java.io.Serializable {

    private Long id;
    private Long prodInvestMentId;
    private String status;
    private java.util.Date created;
    private java.util.Date lastmod;
    private Long version;
    private Long prodId;
    private String customIds;
    private Long salesId;

    public EProdInvestMent() {
    }

    public EProdInvestMent(Long id) {
        this.id = id;
    }

    public EProdInvestMent(Long id, Long prodInvestMentId, String status, java.util.Date created, java.util.Date lastmod, Long version, Long prodId, String customIds, Long salesId) {
        this.id = id;
        this.prodInvestMentId = prodInvestMentId;
        this.status = status;
        this.created = created;
        this.lastmod = lastmod;
        this.version = version;
        this.prodId = prodId;
        this.customIds = customIds;
        this.salesId = salesId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProdInvestMentId() {
        return prodInvestMentId;
    }

    public void setProdInvestMentId(Long prodInvestMentId) {
        this.prodInvestMentId = prodInvestMentId;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getProdId() {
        return prodId;
    }

    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    public String getCustomIds() {
        return customIds;
    }

    public void setCustomIds(String customIds) {
        this.customIds = customIds;
    }

    public Long getSalesId() {
        return salesId;
    }

    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

}
