package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EPROD_APPOINTMENT.
 */
public class EProdAppointment {

    private Long id;
    private Long prodAppointmentId;
    private java.util.Date created;
    private java.util.Date lastmod;
    private Long version;
    private Long salesId;
    private Long prodId;
    private Integer prodQty;
    private Float prodAmount;

    public EProdAppointment() {
    }

    public EProdAppointment(Long id) {
        this.id = id;
    }

    public EProdAppointment(Long id, Long prodAppointmentId, java.util.Date created, java.util.Date lastmod, Long version, Long salesId, Long prodId, Integer prodQty, Float prodAmount) {
        this.id = id;
        this.prodAppointmentId = prodAppointmentId;
        this.created = created;
        this.lastmod = lastmod;
        this.version = version;
        this.salesId = salesId;
        this.prodId = prodId;
        this.prodQty = prodQty;
        this.prodAmount = prodAmount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getProdAppointmentId() {
        return prodAppointmentId;
    }

    public void setProdAppointmentId(Long prodAppointmentId) {
        this.prodAppointmentId = prodAppointmentId;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public java.util.Date getLastmod() {
        return lastmod;
    }

    public void setLastmod(java.util.Date lastmod) {
        this.lastmod = lastmod;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public Long getSalesId() {
        return salesId;
    }

    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    public Long getProdId() {
        return prodId;
    }

    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }

    public Integer getProdQty() {
        return prodQty;
    }

    public void setProdQty(Integer prodQty) {
        this.prodQty = prodQty;
    }

    public Float getProdAmount() {
        return prodAmount;
    }

    public void setProdAmount(Float prodAmount) {
        this.prodAmount = prodAmount;
    }

}
