package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ESALES_APP_PROD.
 */
public class ESalesAppProd implements java.io.Serializable {

    private Long id;
    private Long salesAppProdId;
    private Long salesId;
    private String salesXy;
    private String salesTopsale;
    private String salesOrderamount;
    private String salesPhone;
    private Float prodAmount;

    public ESalesAppProd() {
    }

    public ESalesAppProd(Long id) {
        this.id = id;
    }

    public ESalesAppProd(Long id, Long salesAppProdId, Long salesId, String salesXy, String salesTopsale, String salesOrderamount, String salesPhone, Float prodAmount) {
        this.id = id;
        this.salesAppProdId = salesAppProdId;
        this.salesId = salesId;
        this.salesXy = salesXy;
        this.salesTopsale = salesTopsale;
        this.salesOrderamount = salesOrderamount;
        this.salesPhone = salesPhone;
        this.prodAmount = prodAmount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getSalesAppProdId() {
        return salesAppProdId;
    }

    public void setSalesAppProdId(Long salesAppProdId) {
        this.salesAppProdId = salesAppProdId;
    }

    public Long getSalesId() {
        return salesId;
    }

    public void setSalesId(Long salesId) {
        this.salesId = salesId;
    }

    public String getSalesXy() {
        return salesXy;
    }

    public void setSalesXy(String salesXy) {
        this.salesXy = salesXy;
    }

    public String getSalesTopsale() {
        return salesTopsale;
    }

    public void setSalesTopsale(String salesTopsale) {
        this.salesTopsale = salesTopsale;
    }

    public String getSalesOrderamount() {
        return salesOrderamount;
    }

    public void setSalesOrderamount(String salesOrderamount) {
        this.salesOrderamount = salesOrderamount;
    }

    public String getSalesPhone() {
        return salesPhone;
    }

    public void setSalesPhone(String salesPhone) {
        this.salesPhone = salesPhone;
    }

    public Float getProdAmount() {
        return prodAmount;
    }

    public void setProdAmount(Float prodAmount) {
        this.prodAmount = prodAmount;
    }

}
