package com.finshine.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ETODO_ITEM.
 */
public class ETodoItem implements java.io.Serializable {

    private Long id;
    private Long todoItemId;
    private Long userId;
    private Long startTime;
    private Long endTime;
    private Long customerId;
    private String title;
    private String content;
    private Integer status;

    public ETodoItem() {
    }

    public ETodoItem(Long id) {
        this.id = id;
    }

    public ETodoItem(Long id, Long todoItemId, Long userId, Long startTime, Long endTime, Long customerId, String title, String content, Integer status) {
        this.id = id;
        this.todoItemId = todoItemId;
        this.userId = userId;
        this.startTime = startTime;
        this.endTime = endTime;
        this.customerId = customerId;
        this.title = title;
        this.content = content;
        this.status = status;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getTodoItemId() {
        return todoItemId;
    }

    public void setTodoItemId(Long todoItemId) {
        this.todoItemId = todoItemId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

}
