package com.incito.finshine.entity;

import java.util.Date;

import com.android.core.util.StrUtil;

public class ProdReleasestrategy {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private Long id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.STATUS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private String status;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.CREATED
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private Date created;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.LASTMOD
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private Date lastmod;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.VERSION
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private Long version;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.SALES_IDS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private String salesIds;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column prod_releasestrategy.PROD_ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    private Long prodId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.ID
     *
     * @return the value of prod_releasestrategy.ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.ID
     *
     * @param id the value for prod_releasestrategy.ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.STATUS
     *
     * @return the value of prod_releasestrategy.STATUS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public String getStatus() {
    	if (StrUtil.isBlank(status)) {
			return "";
		}
        return status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.STATUS
     *
     * @param status the value for prod_releasestrategy.STATUS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.CREATED
     *
     * @return the value of prod_releasestrategy.CREATED
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.CREATED
     *
     * @param created the value for prod_releasestrategy.CREATED
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.LASTMOD
     *
     * @return the value of prod_releasestrategy.LASTMOD
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public Date getLastmod() {
        return lastmod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.LASTMOD
     *
     * @param lastmod the value for prod_releasestrategy.LASTMOD
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setLastmod(Date lastmod) {
        this.lastmod = lastmod;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.VERSION
     *
     * @return the value of prod_releasestrategy.VERSION
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.VERSION
     *
     * @param version the value for prod_releasestrategy.VERSION
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.SALES_IDS
     *
     * @return the value of prod_releasestrategy.SALES_IDS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public String getSalesIds() {
    	if (StrUtil.isBlank(salesIds)) {
			return "";
		}
        return salesIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.SALES_IDS
     *
     * @param salesIds the value for prod_releasestrategy.SALES_IDS
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setSalesIds(String salesIds) {
        this.salesIds = salesIds;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column prod_releasestrategy.PROD_ID
     *
     * @return the value of prod_releasestrategy.PROD_ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public Long getProdId() {
        return prodId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column prod_releasestrategy.PROD_ID
     *
     * @param prodId the value for prod_releasestrategy.PROD_ID
     *
     * @ibatorgenerated Sat May 10 20:50:25 CST 2014
     */
    public void setProdId(Long prodId) {
        this.prodId = prodId;
    }
}